---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: pull an image
  docker_image:
    name: $DOCKER_LOGIN/$IMAGE_NAME:$TAG

#- name: "Unarchive backend files"
#  unarchive:
#    src: artifact.tar.gz
#    dest: ~/backend-app

#- name: "Installing project Dependencies"
#  shell: |
#    npm i

- name: "Executing FastAPI app with PM2"
  shell: |
    pm2 stop default
    pm2 start "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app" --name mock-payment-api

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
