version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID


jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - mock-payment-deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
                     ls -la
                     ls -l
                     pwd
                     poetry config virtualenvs.in-project true
            #            poetry shell
                     poetry install
      - save_cache:
          paths: [ /.venv ]
          key: mock-payment-deps-{{ checksum "poetry.lock" }}


workflows:
  default:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
