version: 2.1
orbs:
  slack: circleci/slack@4.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

  notify_on_failure:
    steps:
      - slack/notify:
          event: fail
          channel: cicd-pipeline
          template: basic_fail_1


jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - mock-payment-deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            ls -la
            ls -l
            pwd
            poetry config virtualenvs.in-project true
            poetry install --no-root
      - save_cache:
          paths: [ /.venv ]
          key: mock-payment-deps-{{ checksum "poetry.lock" }}

      - notify_on_failure



  notify_on_success:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job Succeeded. :white_check_mark:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "markdown",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "markdown",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "markdown",
                      "text": "*Branch*:\n$CIRCLE_BRANCH"
                            },
                            {
                      "type": "markdown",
                      "text": "*Commit*:\n$CIRCLE_SHA1"
                    },
                    {
                      "type": "markdown",
                      "text": "*Author*:\n$CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          channel: cicd-pipeline

workflows:
  default:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - notify_on_success:
          requires: [ build ]
