# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID


jobs:
  print-my-work-flow-id:
    docker:
      - image: cimg/node:20.8.0
    steps:
      - checkout
      - print_pipeline_id

  save_hello_world_output:
    docker:
      - image: cimg/node:20.8.0
    steps:
      - checkout
      - run:
          name: "Output hello world to a file"
          command: echo "text to output here" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/node:20.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "Print from a text file"
          command: cat ~/output.txt


workflows:
  hello-world-workflow:
    jobs:
      - print-my-work-flow-id
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output