"""added relationship with transactions to users

Revision ID: 1cf57567a965
Revises: 367bdb7c6b89
Create Date: 2022-09-13 08:32:23.474159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1cf57567a965'
down_revision = '367bdb7c6b89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
