"""added deleted_status to transaction model

Revision ID: 2895d2b8ba0a
Revises: f6c4509401d2
Create Date: 2022-09-13 13:54:10.299795

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2895d2b8ba0a'
down_revision = 'f6c4509401d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('deleted_status', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'deleted_status')
    # ### end Alembic commands ###
