"""added relationship with transactions to user

Revision ID: 29e5950c4cb6
Revises: 1cf57567a965
Create Date: 2022-09-13 08:44:31.242012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '29e5950c4cb6'
down_revision = '1cf57567a965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction', 'user', ['sender_phone'], ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    # ### end Alembic commands ###
