"""created transactions table version 1

Revision ID: 460fa9ccc5e7
Revises: 29c513fc16d4
Create Date: 2022-09-12 12:41:23.103529

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '460fa9ccc5e7'
down_revision = '29c513fc16d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('sender_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'sender_id')
    # ### end Alembic commands ###
