"""created transactions table version 3

Revision ID: 4a441214b9c9
Revises: dc1e95273fce
Create Date: 2022-09-12 14:50:45.943478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4a441214b9c9'
down_revision = 'dc1e95273fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction', 'user', ['sender_phone'], ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    # ### end Alembic commands ###
