"""created transactions table version 2

Revision ID: dc1e95273fce
Revises: 460fa9ccc5e7
Create Date: 2022-09-12 14:39:43.507310

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc1e95273fce'
down_revision = '460fa9ccc5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('transaction_sender_id_fkey', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('sender_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_sender_id_fkey', 'transaction', 'user', ['sender_id'], ['id'])
    op.drop_column('transaction', 'product')
    # ### end Alembic commands ###
