"""added relationship with transactions to user 1

Revision ID: f6c4509401d2
Revises: 29e5950c4cb6
Create Date: 2022-09-13 09:24:58.055316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f6c4509401d2'
down_revision = '29e5950c4cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
